files: pykfp

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - "--config=.flake8"
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        types_or: [ cython, pyi, python ]
        args: [ '--filter-files' ]

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [ "-rn", "-sn", "--rcfile=.pylintrc", "--fail-on=I" ]



