name: PR tests
on:
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - run: poetry check
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - run: poetry install --all-extras
      - run: poetry run pytest
    continue-on-error: true
  build-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: danielavdar.github.io
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - run: poetry check
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry
      - run: make
      - run: make doc
