name: Code Quality

on:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry


      - run: make
      - run: make check
      - run: make mypy
