name: Publish docs
on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  create-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - run: poetry check
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry

      - run: make
      - run: make doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          keep_files: true
