name: Isolation tests
on:
  pull_request:
  workflow_dispatch:
jobs:
  isolation_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: poetry install
      - run: poetry check
      - run: poetry run pytest ./tests/test_iso
    continue-on-error: true
