name: Isolation tests

on:
  pull_request:
  workflow_dispatch:
jobs:
  check-parsed-components:
    name: Components Parsing Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true


      - run: make
      - run: make test
      - run: make check
        continue-on-error: true
      - name: Check for changes
        id: check_changes
        run: |
          if ! git diff --exit-code dummy_components; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Fail if no changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          exit 1
  check-isolation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - run: uv build
      - run: pip install dist/*.whl
      - run: python -m dummy_components.check_imports
    continue-on-error: true
