name: Isolation tests

on:
  pull_request:
  workflow_dispatch:
jobs:
  check-parsed-components:
    name: Components Parsing Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry


      - run: make
      - run: make test
      - run: make check
        continue-on-error: true
      - name: Check for changes
        id: check_changes
        run: |
          if ! git diff --exit-code dummy_components; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Fail if no changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          exit 1
  check-isolation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - run: poetry check
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: poetry build
      - run: pip install dist/*.whl
      - run: python -m dummy_components.check_imports
    continue-on-error: true
