name: Publish Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - run: poetry install
      - name: All tests
        run: poetry run pytest
      - name: Stamp Version
        run: poetry version ${{ github.ref_name }}
      - name: Build
        run: poetry build
      - name: Set Token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      - name: Publish
        run: poetry publish
